### ISSUE TITLE
Make an Installation Script (with global variables)

### ISSUE THREAD

**Issue by a7hybnj2** [brandflake11/Retropie-Airplane-Mode#3]
The configuration file needs to be the answers to the questions so they can be modified later.

The current state is needed because there needs to be a check on `enable` and `disable` to see if bluetooth and/or wifi is already off. Especially once the files are getting renamed or else your going to end up loosing the state of the icon and the airplane mode icon will be shown when wifi or bluetooth is on.

Questionnaire on installation:

`permanently disable expi boot video?`
`enable airplane mode icon?`

**Comment by brandflake11** [comment]
I would much rather have one simple question in the installation script based on if the Piboy hardware is detected in /proc (still need to figure out how to do this): `Do you want Airplane-mode to affect the osd?
`
We won't need to disable the expi boot video, as the airplane-mode scripts will rename the file, and then name it back. I will leave it up to people to disable the startup boot video if they want to, I think that goes outside the scope of this script project. I will keep this in mind though! :)

**Comment by a7hybnj2** [comment]
Good point. Don't want to overextend.

**Comment by brandflake11** [comment]
This is done!
