### ISSUE TITLE
Airplane mode icon

### ISSUE THREAD

**Issue by a7hybnj2** [brandflake11/Retropie-Airplane-Mode#4]
I will work on an icon. It will look like an airplane and in the style of the existing icons. I will make several version and we can dial them in here.

**Comment by a7hybnj2** [comment]
How do you feel about a jet? I haven't loaded it into my osd yet but I suspect it should work.
![ic_airplane_white_13dp](https://user-images.githubusercontent.com/36831279/106044380-aa6fe280-60ad-11eb-935b-7eabba2331c9.png)

This is v1 I am open to any ideas you have. I will eventually need to make this in small med and large icon sizes but we should dial in the idea before I do that. This is medium size.

**Comment by a7hybnj2** [comment]
It looks cool but slightly undersized: 
![pic](https://user-images.githubusercontent.com/36831279/106045495-fec79200-60ae-11eb-86c4-b5448c453dd3.jpeg)

I added `/home/pi` to my `/ect/samba/smb.conf` to make overriding assets easier.

```
[HOME]
comment = HOME
path = "/home/pi"
writable = yes
guest ok = yes
create mask = 0644
directory mask = 0755
force user = pi
```

**Comment by a7hybnj2** [comment]
Bigger test
![pic](https://user-images.githubusercontent.com/36831279/106069943-8625fd00-60d1-11eb-9db5-28aedae6afdf.jpeg)

**Comment by brandflake11** [comment]
That looks really good. Did you make it yourself? If you want to, send a pull request and put it in .icongit and we can implement it in the scripts. Also, we can convert it into an .svg file in the .icongit and then make the different sizes if you are feeling up to it.

**Comment by a7hybnj2** [comment]
Yea I made it. My goal was simple straight lines which is why I went with a jet. It's already a vector so making different sizes will be easy. I will make the other sizes and do a pr for all at once. If you wanted to test it before I get to a computer you can save the .png from the above issue.

**Comment by brandflake11** [comment]
I greatly appreciate your work on this! The jet looks great. I'm going to finish the update script first, then work on changing the icons!

What name would you like to use to be credited in the readme?
