### ISSUE TITLE
Update Script can't yet find the Piboy variable

### ISSUE THREAD

**Issue by brandflake11** [brandflake11/Retropie-Airplane-Mode#6]
As of yet, I am figuring out how to load the needed variable to get the update script to not ask the question of whether you want RetroPie-airplane-mode to manage your osd. It asks even when the variable is in the bashrc. Currently, there is a thread open on the retropie forums: https://retropie.org.uk/forum/topic/29490/does-emulationstation-load-bashrc/4

I may just get the script to read the variable in the bashrc, or create a separate file.

**Comment by a7hybnj2** [comment]
I guess I would have done a stand alone file. Something in `.config`.

**Comment by brandflake11** [comment]
Since I haven't discovered how to do this yet, I'm going to go with a .config file in /home/pi/RetroPie/retropiemenu/wireless

**Comment by a7hybnj2** [comment]
Cool. Yea you can put it wherever but traditionally I see them in `/home/pi/.airplanerc` or `/home/pi/.config/airplane.cfg`. But it doesn't really matter unless you are trying to go with a standard dotfile config format...

**Comment by brandflake11** [comment]
That is true, I just don't want to touch people's configs too much. I think it would be better to stay in the folder where the scripts lie, and then if people want, they can copy their whole Retropie folder over and keep everything in it if they want to sync the scripts with another computer.

**Comment by a7hybnj2** [comment]
Maybe if it is already buried in your script folder then don't hide it. Just make it config.txt or airplane.cfg...

**Comment by brandflake11** [comment]
I want to hide it I think
