### ISSUE TITLE
Remove bluetooth from OSD by disabling services

### ISSUE THREAD

**Issue by rdsngit** [brandflake11/Retropie-Airplane-Mode#7]
The on-screen-display (OSD) for the PiBoy DMG will only hide the bluetooth icon if bluetooth is disabled.

In explanation in the `osd.cfg` file on the Experimental Pi webpage it shows that the bluetooth icon remains displayed when it is enabled both when it is active or idle.

https://resources.experimentalpi.com/customizing-the-piboys-on-screen-display/

Would you consider adding optional scripts for those who would like the icon removed from the OSB and disable bluetooth services?

This advice was adapted from the following webpage, so all credit for this goes to the author. https://di-marco.net/blog/it/2020-04-18-tips-disabling_bluetooth_on_raspberry_pi/

```sh
sudo systemctl stop bluetooth
sudo systemctl disable hciuart.service
sudo systemctl disable bluealsa.service
sudo systemctl disable bluetooth.service
sudo reboot
```

And there would need to be a corresponding enable script as well.

**Comment by brandflake11** [comment]
Hello @rdsngit,

Are you saying that the osd relies on the systemd service being disabled for it to not show it in the osd? I'm not quite sure what you mean, as it looks like you are showing me two things at once. 

I really wanted the script to manage the OSD for you (which is why it should ask if you want that if you're on a Piboy), but I never got around to doing it. It would use sed to comment out lines in the osd.cfg file. I started working on this, but never finished or implemented it in any working manner. We even have a nice airplane icon. 

As far as stopping the bluetooth systemd services, I don't think that is necessary. My scripts use rfkill to stop the hardware from transmitting wireless, so stopping the services themselves doesn't seem necessary to me. Is there any reason to do that as well? I can definitely consider if so.

Thanks for the issue and looking forward to a response.

**Comment by rdsngit** [comment]
Yes, the Bluetooth icon will still be displayed if you just stop the service. 

This image is from https://resources.experimentalpi.com/customizing-the-piboys-on-screen-display/

![osd_file.png](https://user-images.githubusercontent.com/52106678/120900797-d50b1280-c62e-11eb-9244-b6d8bd6f6c51.png)

I checked this using commands like:

```sh
sudo systemctl stop bluetooth
sudo systemctl status bluetooth
```

It showed in the command line that the Bluetooth service was inactive. Then after exiting from the command line and checking the OSD in the main Emulation Station UI the Bluetooth icon was still present. I also tried your scripts that use `rfkill` too.

I don't know if the instructions for disabling Bluetooth on the Experimental Pi website work. It is suggested that by adding the following line to the `/boot/config.txt` it would disable Bluetooth, but it didn't when I tried this.

```
dtoverlay=disable-bt
```

As for disabling the Bluetooth services, as removing as the Bluetooth icon from the OSD another benefit could be battery life (although I don't know how much of a saving it would be). I'm also not sure if your scripts turn off Bluetooth so it stays off after turning a PiBoy off to safe shutdown and then on again, but disabling the services did keep it off after reboots from my testing last night.

For my use, I am unlikely to use Bluetooth much so having it disabled suits me. I understand others might use Bluetooth more than me and disabling the services and rebooting might not be what they want to do.

My example commands in this issue description were really just to show you what worked for me after an evening of trial and error. You might have some ideas for an alternative implementation for the same goal of removing the Bluetooth icon when not in use.

**Comment by rdsngit** [comment]
Here is the readme from the overlays section of the Raspberry Pi firmware showing the comment about having to disable the systemd service.

https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README

```
Name:   disable-bt
Info:   Disable onboard Bluetooth on Pi 3B, 3B+, 3A+, 4B and Zero W, restoring
        UART0/ttyAMA0 over GPIOs 14 & 15.
        N.B. To disable the systemd service that initialises the modem so it
        doesn't use the UART, use 'sudo systemctl disable hciuart'.
Load:   dtoverlay=disable-bt
Params: <None>
```

**Comment by brandflake11** [comment]
Yes, it makes sense that disabling the bluetooth systemd service would display bluetooth as inactive in systemctl; systemctl displays systemd services. rfkill should do the job just fine as well without disabling the system's bluetooth service. If you find and can show me that there is a significant battery increase by disabling the systemd bluetooth service, I'll go ahead and add the commands `systemctl stop bluetooth` and `systemctl disable bluetooth` to the disable_bluetooth script, and `systemctl start bluetooth` and `systemctl enable bluetooth` to the enable_bluetooth script. However, I don't see why this would make much difference if rfkill turns off the hardware. The bluetooth service probably isn't hurting anything when the bluetooth hardware is off.

**Comment by rdsngit** [comment]
I'll close this issue and thanks for taking the time to consider these details.

**Comment by brandflake11** [comment]
@rdsngit Thanks for reaching out for the suggestion. If you want to disable the bluetooth systemd services, you can always add those commands to the respective scripts and then you won't need another script to disable bluetooth services. If you need help with that, let me know and I can give you some terminal commands you can input to add them to your scripts.

**Comment by rdsngit** [comment]
Cheers @brandflake11 , I've forked this repo and added disabling the Bluetooth services to scripts in that. I have it working on my PiBoy now so there's no Bluetooth icon when it isn't being used :)

What you created here is a great start at Airplane mode, and could evolve further such as with an airplane icon. Really like how it is added to the Settings menu in the PiBoy UI and this approach has potential for adding further customisation to the menu.

**Comment by brandflake11** [comment]
Wait, I'm confused now. Does disabling the bluetooth service disable the osd icon, or does it only change when you restart the device and the service is disabled?

If it disables the bluetooth icon, then I'd consider adding it to the scripts.
